#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use rss\worker\commands\FetchCommand;
use rss\worker\commands\FetchAllCommand;

require __DIR__.'/bootstrap.php';

$application = new Application();
$application->add(new FetchCommand($mapper, $channelsFinder, $itemsFinder));
$application->add(new FetchAllCommand($channelsFinder));
$application->run();